make use of cibuildwheel

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,91 +1,79 @@
 # Config file for automatic testing at travis-ci.org
 
 language: python
-language: python
+
+env:
+  global:
+    # CIBW_BEFORE_TEST run before wheel installed...
+    # - CIBW_BEFORE_TEST="python -c \"from sgp4 import api; print('accelerated API:', api.accelerated);\""
+    - CIBW_TEST_COMMAND='python -c "from sgp4 import api; print(\"accelerated API:\", api.accelerated);"; python -m sgp4.tests'
+    - CIBW_BUILD_VERBOSITY=1
+    - CIBW_BUILD="cp36-*"
 
 jobs:
   include:
 
     # perform a linux build
     - name: "Linux Python 3.5"
-      python: 3.5
-      # os: linux
-      # services: docker
+      services: docker
 
     # and a mac build
-    - name: "MacOS clang vanilla Python 2.7"
+    - name: "MacOS clang vanilla"
       os: osx
-      osx_image: xcode9.3  # Python 2.7.14_2
       language: shell
+      # before_install:
+      #   - brew update
+      #   - brew install libomp
       env:
-        - COMPILER='clang'
+        - CIBW_BEFORE_BUILD="brew update; brew install libomp"
 
-    - name: "MacOS clang vanilla Python 3.7"
+    - name: "MacOS gcc"
       os: osx
-      osx_image: xcode11.2  # Python 3.7.4
       language: shell
-      env:
-        - COMPILER='clang'
-
-    - name: "MacOS gcc Python 3.7"
-      os: osx
-      osx_image: xcode11.2  # Python 3.7.4
-      language: shell
-      env:
-        - COMPILER='gcc'
+      before_install:
+        # - brew update
+        # - brew install gcc
+        # - brew link --overwrite gcc
+        - gcc --version
+        # not sure, if the following can be improved
+        - gcc-6 --version && export CC="gcc-6" && export LD="gcc-6" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/6/" || true
+        - gcc-7 --version && export CC="gcc-7" && export LD="gcc-7" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/7/" || true
+        - gcc-8 --version && export CC="gcc-8" && export LD="gcc-8" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/8/" || true
+        - gcc-9 --version && export CC="gcc-9" && export LD="gcc-9" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/9/" || true
+        - gcc-10 --version && export CC="gcc-10" && export LD="gcc-10" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/10/" || true
 
     # and a windows build
-    - name: "Windows Python 2.7.18"
-      os: windows
-      language: shell
-      before_install:
-        - choco install python2
-        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
-
-    - name: "Windows Python 3.5"
-      os: windows
-      language: shell
-      before_install:
-        - choco install python3 --version 3.5.4
-        - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"
-
-    - name: "Windows Python 3.8"
+    - name: "Windows"
       os: windows
       language: shell
       before_install:
         - choco install python3 --version 3.8.0
         - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
 
-before_install:
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $COMPILER == "clang" ]]; then brew update; brew install libomp; fi
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $COMPILER == "llvm" ]]; then brew update; brew install llvm; fi
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $COMPILER == "gcc" ]]; then brew update; brew install gcc; brew link --overwrite gcc; fi
-  # not sure, if the following can be improved
-  - 'if [[ $TRAVIS_OS_NAME == "osx" && $COMPILER == "gcc" ]]; then
-       gcc --version;
-       gcc-6 --version && export CC="gcc-6" && export LD="gcc-6" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/6/" || true;
-       gcc-7 --version && export CC="gcc-7" && export LD="gcc-7" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/7/" || true;
-       gcc-8 --version && export CC="gcc-8" && export LD="gcc-8" && export LDFLAGS="-Wl,-rpath,/usr/local/opt/gcc/lib/gcc/8/" || true;
-     fi'
 
 install:
-  - "pip install -vv -e ."
-  # - "python setup.py install"
-  - "pip install pyflakes"
+  - python -m pip install cibuildwheel
 
 script:
-  # check if accelerated api is available:
-  - python -c "from sgp4 import api; print('accelerated API:', api.accelerated);"
-  # We invoke the tests directly instead of using "-m discover" because
-  # that would set the current working directory to the "sgp4/" package
-  # itself, allowing "io.py" to shadow the real io module and thereby
-  # causing failure when NumPy tries to import.
-  - python -m sgp4.tests
-  # - pyflakes $(find sgp4/ -name '*.py')
-  # - |-
-  #   if grep ' $' $(find extension/ sgp4/ -type f) ;then echo ERROR: TRAILING WHITESPACE; exit 0 ;fi
-
-after_success:
-  - python -m pip install twine cibuildwheel==1.1.0
   # build the wheels, put them into './wheelhouse'
+  # cibuildwheel will test a variety of python versions!
   - python -m cibuildwheel --output-dir wheelhouse
+
+
+
+# install:
+#   # - "pip install -vv -e ."
+#   - "python setup.py install"
+#   - "pip install pyflakes"
+
+# script:
+#   # check if accelerated api is available:
+#   - python -c "from sgp4 import api; print('accelerated API:', api.accelerated);"
+#   # We invoke the tests directly instead of using "-m discover" because
+#   # that would set the current working directory to the "sgp4/" package
+#   # itself, allowing "io.py" to shadow the real io module and thereby
+#   # causing failure when NumPy tries to import.
+#   - python -m sgp4.tests
+#   # - pyflakes $(find sgp4/ -name '*.py')
+#   # - |-
+#   #   if grep ' $' $(find extension/ sgp4/ -type f) ;then echo ERROR: TRAILING WHITESPACE; exit 0 ;fi
